version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - 8009:80
    volumes:
      - ./public_html:/public_html
      - ./conf.d:/etc/nginx/conf.d
  php:
    image: php:8.2-fpm-alpine3.16
    volumes:
      - ./public_html:/public_html
    expose:
      - 9000
